In [4]:
import pyautogui
import clipboard
import pandas


pyautogui.PAUSE = 0.3

#Abrir planilha com os Micro e colocar o código como variavel
tabela_itens = pandas.read_excel("Micros.xlsx")


#localizar Logix 
x, y, largura, altura = pyautogui.locateOnScreen("logix.png", grayscale=True, confidence=0.9)

#Abrir Logix(Já vai estar no sup0170)
pyautogui.click(x + largura/2, y + altura/2)

#Loop para cada item
for i in range(2):
 
    #Clicar C para consultar
    pyautogui.press("c")
    
    #Escrever código do item
    pyautogui.write(str(tabela_itens["Codigo"][i]))
    #pyautogui.write(str(tabela_itens[Codigo][linha]))

    #Fecha busca o item e fecha tela dos lotes
    pyautogui.press("esc")
    
    #Fechar no X vermelho
        #localizar x
    x, y, largura, altura = pyautogui.locateOnScreen("x.png", grayscale=True, confidence=0.9)
        #Clicar no x
    pyautogui.click(x + largura/2, y + altura/2)

    #localizar Qtd_em_terceiros 
    x, y, largura, altura = pyautogui.locateOnScreen("qtd_terceiros.png", grayscale=True, confidence=0.8)

    #Clicar com botao direito
    pyautogui.rightClick(x + largura, y + altura)

    #localizar e clicar SelectAll
    x, y, largura, altura = pyautogui.locateOnScreen("select_all.png", grayscale=True, confidence=0.95)
    pyautogui.click(x + largura/2, y + altura/2)

    #Copiar o valor
    #localizar Qtd_em_terceiros 
    x, y, largura, altura = pyautogui.locateOnScreen("qtd_terceiros.png", grayscale=True, confidence=0.8)
    #Clicar com botao direito
    pyautogui.rightClick(x + largura, y + altura)
    #copiar
    x, y, largura, altura = pyautogui.locateOnScreen("copiar.png", grayscale=True, confidence=0.95)
    pyautogui.click(x + largura/2, y + altura/2)

    #Armazena na tabela
    tabela_itens["Quantidade"][i]= clipboard.paste()

# Transformar a tabela para o Excel Novamente
tabela_itens.to_excel("Micro.xlsx", index=False)

    Codigo
0    21088
1    40355
2    29115
3    38807
4    12625
5    48032
6    30329
7    48112
8    24531
9     9687
10    5650
11   37802
12   40851
13   42852
14   42013
15   46499
16   42012
17   12678
18   34002
19   49316
20   24499
21   32233
22   42646
23   42950

codigo